language: node_js
node_js:
  - "^6.9.1"
script:
  - npm install --depth=0
  - bower install
  - gulp
install:
  - npm install -g firebase-tools bower gulpjs/gulp#4.0
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN} --project global-hack-6
