language: node_js
node_js:
  - "6.9.1"
script:
  - npm install
  - bower install
  - gulp
install:
  - npm install -g firebase-tools bower gulpjs/gulp#4.0
after_success:
  - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD} --project global-hack-6
